- src/Presentation/Console/Commands/InitProjectCommand.php
[SDK-317](https://spryker.atlassian.net/browse/SDK-317)
> SDK-317: Extra value for context_dir setting after initializing new project

- src/Presentation/Console/Resources/config/services.yaml
- src/Presentation/Ide/PhpStorm/Dto/Param.php
- src/Presentation/Ide/PhpStorm/Mapper/CommandMapper.php
- src/Presentation/Ide/PhpStorm/Service/CommandLoader.php
- src/Presentation/Ide/PhpStorm/Service/ConfigManager.php
- tests/Sdk/Tests/Presentation/Ide/PhpStorm/Formatter/CommandXmlFormatterTest.php
- tests/Sdk/Tests/Presentation/Ide/PhpStorm/Mapper/CommandMapperTest.php
- tests/Sdk/Tests/Presentation/Ide/PhpStorm/Mapper/OptionMapperTest.php
- tests/Sdk/Tests/Presentation/Ide/PhpStorm/Mapper/ParamMapperTest.php
- tests/Sdk/Tests/Presentation/Ide/PhpStorm/Service/CommandLoaderTest.php
- tests/Sdk/Tests/Presentation/Ide/PhpStorm/Service/ConfigManagerTest.php
- tests/_support/UnitTester.php
[SDK-364](https://spryker.atlassian.net/browse/SDK-364)
> SDK-364: Increase code coverage: Sdk\Presentation\Ide

- frontend/libs/stylelint.js
- src/Extension/Tasks/ScssLinterFixerTask.yaml
- src/Extension/Tasks/ScssLinterTask.yaml
Added default codestyle config and command-line option for providing custom one.
> SDK-408 Added command line option for custom codestyle config

- bin/spryker-sdk.sh
- src/Infrastructure/Repository/Violation/Formatters/OutputViolationReportFormatter.php
> SDK-322 release stabilization

- src/Core/Appplication/Dto/Violation/Violation.php
- src/Core/Appplication/Service/ContextSerializer.php
- src/Extension/Converters/CheckstyleViolationReportConverter.php
- src/Extension/Converters/ESLintViolationReportConverter.php
- src/Extension/Converters/FrontendSnifferViolationReportConverter.php
- src/Extension/Converters/PHPMDViolationConverter.php
- src/Extension/Converters/PhpBenchReportConverter.php
- src/Extension/Converters/PhpStanViolationConverter.php
- src/Extension/Converters/PrettierSnifferViolationReportConverter.php
- src/Extension/Converters/ScssLinterViolationReportConverter.php
- src/Extension/Converters/SecurityViolationReportConverter.php
- src/Infrastructure/Mapper/ViolationReportFileMapper.php
- tests/_support/Helper/Core/Application/Service/ContextSerializerHelper.php
[SDK-493](https://spryker.atlassian.net/browse/SDK-493)
> SDK-493: Refactored creation of Violation

- src/Presentation/Console/Commands/InitProjectCommand.php
- src/Presentation/Console/Commands/InitSdkCommand.php
- src/Presentation/Console/Commands/RunTaskWrapperCommand.php
- src/Presentation/Console/Commands/RunWorkflowCommand.php
- src/Presentation/Console/Commands/SettingSetCommand.php
- tests/Sdk/Acceptance/Extension/Tasks/ESLintTaskCest.php
- tests/Sdk/Acceptance/Extension/Tasks/UpgraderTaskCest.php
- tests/_support/AcceptanceTester.php
- fixed failing acceptance tests
- changed commands to use execute instead of run
> SDK-507: Tests and commands fixes

- src/Infrastructure/Service/CliValueReceiver.php
https://spryker.atlassian.net/browse/APPS-4264
> APPS-4264 Dev DX improvements

- app/Migrations/Version20220607125416.php
- src/Core/Domain/Entity/Command.php
- src/Infrastructure/Mapper/CommandMapper.php
- src/Infrastructure/Repository/TaskYamlRepository.php
- src/Infrastructure/Resources/config/doctrine/Command.orm.yml
- src/Infrastructure/Service/LocalCliRunner.php
- src/Infrastructure/Service/PhpCommandRunner.php
- tests/Sdk/Unit/Infrastructure/Mapper/CommandMapperTest.php
- tests/_support/UnitTester.php
Ticket: [SDK-577](https://spryker.atlassian.net/browse/SDK-577)
> SDK-577: ErrorCommandInterface::getErrorMessage not used

- build/infrastructure/sdk.debug.Dockerfile
- build/infrastructure/sdk.local.Dockerfile
- docker-compose.yml
- infrastructure/create_release.sh
- src/Core/Appplication/Service/ProjectWorkflow.php
- src/Extension/Settings/settings.yaml
- src/Presentation/Console/Commands/RunWorkflowCommand.php
- tests/Sdk/Unit/Core/Application/Service/ProjectWorkflowTest.php
[https://spryker.atlassian.net/browse/SDK-553](https://spryker.atlassian.net/browse/SDK-553)
> SDK-553 Override YAML configuration with another YAML

- composer.json
- composer.lock
- src/Presentation/Console/Commands/UpdateCommand.php
https://spryker.atlassian.net/browse/SDK-628
> SDK-628: Added client for get last version

- build/infrastructure/sdk.Dockerfile
- infrastructure/sdk.Dockerfile
Task: https://spryker.atlassian.net/browse/SDK-685
> SDK-685 Added bootstrap.php to dockerfile

- app/Migrations/Version20220614195816.php
Task https://spryker.atlassian.net/browse/SDK-720
> SDK-720 Updated migration and added missing db relation.

- infrastructure/sdk.Dockerfile
- src/Presentation/Console/Commands/InitSdkCommand.php
- src/Presentation/Console/Commands/UpdateSdkCommand.php
Task https://spryker.atlassian.net/browse/SDK-708
> SDK-691 Fixed sub-processes timeout and added missed cache warmup.

- src/Extension/Tasks/PhpStanTask.yaml
Ticket: https://spryker.atlassian.net/browse/APPS-4768
> [APPS-4768] PHPStan fixes

- composer.json
- composer.lock
- src/Core/Appplication/Dependency/ReportRepositoryInterface.php
- src/Core/Appplication/Dependency/ViolationReportRepositoryInterface.php
- src/Core/Appplication/Service/Report/ReportGeneratorInterface.php
- src/Core/Appplication/Service/Report/ReportGeneratorResolverInterface.php
- src/Core/Appplication/Service/ReportGeneratorFactory.php
- src/Core/Appplication/Service/Violation/ViolationReportGenerator.php
- src/Core/Appplication/Service/Violation/ViolationReportGeneratorResolver.php
- src/Core/Appplication/Service/Violation/ViolationReportMerger.php
- tests/Sdk/Unit/Core/Application/Service/ReportGeneratorFactoryTest.php
https://spryker.atlassian.net/browse/SDK-770
> SDK-770 move report interfaces

- composer.lock
- src/Core/Appplication/Dependency/ReportRepositoryInterface.php
- src/Core/Appplication/Service/Report/ReportGeneratorInterface.php
- src/Core/Appplication/Service/Report/ReportGeneratorResolverInterface.php
- src/Core/Appplication/Service/ReportGeneratorFactory.php
- src/Core/Appplication/Service/Violation/ViolationReportGenerator.php
- src/Core/Appplication/Service/Violation/ViolationReportGeneratorResolver.php
- src/Core/Appplication/Service/Violation/ViolationReportMerger.php
- tests/Sdk/Unit/Core/Application/Service/ReportGeneratorFactoryTest.php
[SDK-768](https://spryker.atlassian.net/browse/SDK-768)
> SDK-768: Reports unification/abstraction

- docs/conventions.md
Dear colleagues. 
I've provided additional conventions. Any constructive ideas, objections, and improvements are more than welcome!
Ticket: https://spryker.atlassian.net/browse/SDK-754
> SDK-754: Introduced naming and console command structure conventions.

- infrastructure/create_release.sh
- src/Presentation/Console/Command/UpdateSdkCommand.php
Ticket: https://spryker.atlassian.net/browse/SDK-815
> SDK-815: Fixed release script to create missed folders and update command to return proper code.

- .github/workflows/ci.yml
- composer.lock
- config/packages/workflow.yaml
- src/Extension/Task/AcpAppAsyncApiCodeGenerateTask.yaml
- src/Extension/Task/AcpAppOpenApiCodeGenerateTask.yaml
- src/Extension/Task/AppValidationTaskSet.yaml
- src/Extension/Task/CodesnifferFixerTask.yaml
- src/Extension/Task/CodesnifferTask.yaml
- src/Extension/Task/PhpMdTask.yaml
- src/Extension/Task/RunInstallTask.yaml
- src/Extension/ValueResolver/AppTypeValueResolver.php
- tests/Sdk/Unit/Extension/ValueResolver/AppTypeValueResolverTest.php
- Updated App Workflow.
- Use Mini Framework as starting repository.
> Updated ACP related stuff.

- src/Extension/Task/DeprecationsCheckTask.yaml
Ticket: https://spryker.atlassian.net/browse/SDK-659
Changes regarding comment https://spryker.atlassian.net/browse/SDK-756?focusedCommentId=319063
> SDK-756:  Improved description for the 'validation:php:deprecations-check' task.

- composer.json
- composer.lock
- docker-compose.yml
- extension/Hello/Resources/config/workflow.yaml
- src/Extension/Resources/config/services.yaml
- src/Extension/Workflow/TransitionBooleanResolver.php
- src/Infrastructure/Event/Workflow/WorkflowTransitionListener.php
- src/Infrastructure/Resources/config/services.yaml
- src/Infrastructure/Service/WorkflowTransitionResolverRegistry.php
- tests/Sdk/Unit/Infrastructure/Event/Workflow/WorkflowTransitionListenerTest.php
- tests/Sdk/Unit/Infrastructure/Service/WorkflowTransitionResolverRegistryTest.php
https://spryker.atlassian.net/browse/SDK-832
> SDK-832 refactor workflow listener

- bin/spryker-sdk.sh
- docker-compose.yml
- docs/workflow.md
- src/Presentation/Console/Command/ShowWorkflowCommand.php
- src/Presentation/Console/Resources/config/services.yaml
https://spryker.atlassian.net/browse/SDK-844
> SDK-844 fix workflow command and docs

- docs/conventions.md
Ticket: https://spryker.atlassian.net/browse/SDK-851
This is just a draft and has to be discussed. You are welcome to left a comment.
> SDK-851: Introduced convention for the sdk contracts.

- infrastructure/installer_header.sh
https://spryker.atlassian.net/browse/SDK-947
> SDK-947 fix shell if statement

- src/Presentation/Console/Command/QaAutomationCommand.php
- src/Presentation/Console/Command/RunTaskWrapperCommand.php
https://spryker.atlassian.net/browse/SDK-951
> SDK-951 initialized workflow blocks task execution

- src/Extension/Resources/config/task/AcpAppAsyncApiAddMessageSchemaTask.yaml
- src/Extension/ValueResolver/ArrayOptionValueResolver.php
- src/Extension/ValueResolver/StaticValueResolver.php
- tests/Sdk/Unit/Extension/ValueResolver/StaticTextValueResolverTest.php
- tests/Sdk/Unit/Extension/ValueResolver/StaticValueResolverTest.php
> SDK-00: Depricated ArrayOptionValueResolver and improved StaticValueResolver.

- infrastructure/sdk.Dockerfile
https://spryker.atlassian.net/browse/SDK-977
> SDK-977 workflow issue fix

- README.md
- infrastructure/installer_header.sh
https://spryker.atlassian.net/browse/SDK-988
> SDK-988 self update script

- .env
- .env.dist
- docker-compose.yml
- infrastructure/installer_header.sh
- infrastructure/sdk.Dockerfile
Ticket: https://spryker.atlassian.net/browse/SDK-986
> SDK-986 update infrastructure

- src/Infrastructure/ManifestValidator/TaskManifestConfiguration.php
- src/Infrastructure/ManifestValidator/TaskSetManifestConfiguration.php
- src/Infrastructure/Repository/TaskYamlRepository.php
https://spryker.atlassian.net/browse/SDK-1009
> SDK-1009 update manifest validator

- composer.json
- composer.lock
- docs/development.md
- docs/profiler.md
- infrastructure/debug/php/xhprof.ini
- infrastructure/debug/sdk.sh
- infrastructure/sdk.debug.Dockerfile
- src/Infrastructure/Event/Profiler/ProfilerEventListener.php
- src/Infrastructure/Resources/config/services.yaml
https://spryker.atlassian.net/browse/SDK-1017
> SDK-1017 dev profiler tool

- src/Core/Application/Dependency/Repository/SettingRepositoryInterface.php
- src/Core/Application/Dependency/SettingFetcherInterface.php
- src/Core/Application/Resources/config/services.yaml
- src/Core/Application/Service/ProjectWorkflow.php
- src/Extension/Resources/config/services.yaml
- src/Extension/Setting/Initializer/ProjectWorkflowInitializer.php
- src/Infrastructure/Repository/ContextFileRepository.php
- src/Infrastructure/Repository/ProjectSettingRepository.php
- src/Infrastructure/Repository/SettingRepository.php
- src/Infrastructure/Resources/config/services.yaml
- src/Infrastructure/Service/DefaultContextReceiver.php
- src/Infrastructure/Service/DynamicTaskSetCreator.php
- src/Infrastructure/Setting/SettingFetcher.php
- src/Presentation/Console/Command/RunWorkflowCommand.php
- src/Presentation/Console/Resources/config/services.yaml
- tests/Sdk/Unit/Core/Application/Service/ProjectWorkflowTest.php
- tests/Sdk/Unit/Extension/Setting/Initializer/ProjectWorkflowInitializerTest.php
- tests/Sdk/Unit/Infrastructure/Repository/ContextFileRepositoryTest.php
- tests/Sdk/Unit/Infrastructure/Repository/ProjectSettingRepositoryTest.php
https://spryker.atlassian.net/browse/SDK-982
> SDK-982 refactor project setting repository

- composer.lock
> Update upgrader version

- composer.json
- composer.lock
- src/Extension/Setting/Initializer/CreateDirectoryInitializer.php
- src/Extension/Setting/Initializer/ProjectUuidInitializer.php
- src/Extension/Setting/Initializer/ProjectWorkflowInitializer.php
Ticket: https://spryker.atlassian.net/browse/SDK-1078
> SDK-1078: Updated sdk-contacts version and initializers.

- src/Extension/Resources/config/task/SprykBuildTask.yaml
- tests/Sdk/Acceptance/Extension/Task/SprykBuildTaskCest.php
- tests/_support/AcceptanceTester.php
[SDK-1077](https://spryker.atlassian.net/browse/SDK-1077)
> SDK-1077: Create task to expose `spryk-build`

- src/Extension/Resources/config/task/SprykDumpTask.yaml
- tests/Sdk/Acceptance/Extension/Task/SprykDumpTaskCest.php
[SDK-1075](https://spryker.atlassian.net/browse/SDK-1075)
> SDK-1075: Create task to expose `spryk-dump`

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- phpcs.xml
Ticket: https://spryker.atlassian.net/browse/SDK-1158.
> SDK-1158: Introduced PR template.

- docs/vsc.md
- src/Extension/Task/Command/VcsCloneCommand.php
- src/Extension/Task/VcsCloneTask.php
https://spryker.atlassian.net/browse/SDK-1271
> SDK-1271: Create doc for VCS

- bin/spryker-sdk.sh
- infrastructure/sdk.Dockerfile
- infrastructure/sdk.debug.Dockerfile
- infrastructure/sdk.local.Dockerfile
Ticket: https://spryker.atlassian.net/browse/SDK-1273.
> SDK-1273: Improved docker files

- composer.lock
Ticket: [https://spryker.atlassian.net/browse/PPLUS-1709].
> PPLUS-1709: Update upgrader and integrator

- src/Extension/Resources/config/services.yaml
- src/Extension/Task/Command/VcsCloneCommand.php
- src/Extension/Task/VcsCloneTask.php
Ticket: https://spryker.atlassian.net/browse/SDK-1325.
> SDK-1325: Fixed mkdir for VCS clone

- docs/rest_api.md
Ticket: [SDK-1328](https://spryker.atlassian.net/browse/SDK-1328)
> SDK-1328 update rest api doc

- bin/spryker-sdk.sh
Ticket: https://spryker.atlassian.net/browse/SDK-1331.
> SDK-1331: removed local composer install

- infrastructure/sdk.debug.Dockerfile
> SDK-00: Removed xhprof installation from dev Docekrfile.

- .github/workflows/ci.yml
- README.md
> Add Codecov step to CI pipeline

- composer.lock
Ticket: https://spryker.atlassian.net/browse/SDK-1573.
> SDK-1573: Update upgrader

- composer.lock
Add composer configuration for upgrader
> SDK-1573: Add composer configuration for upgrader

- composer.lock
Update upgrader and integrator
> SDK-1606: Update integrator and upgrader

- composer.lock
Update upgrader and integrator
> PPLUS-1860: Update upgrader and integrator

- composer.lock
> PPLUS-1860: Revert plugin version update

- composer.lock
Ticket: https://spryker.atlassian.net/browse/SDK-1610 .
> SDK-1610: Update ugrader and integrator

- composer.lock
Ticket: https://spryker.atlassian.net/browse/SDK-1689
> SDK-1689: Fixed wrapped method integration in the integrator.

- src/Extension/Resources/config/task/SprykBuildTask.yaml
- src/Extension/Resources/config/task/SprykDumpTask.yaml
- src/Extension/Resources/config/task/SprykRunTask.yaml
Ticket: https://spryker.atlassian.net/browse/SDK-1690
- sdk spryk usage
> SDK-1690: Spryk uses sdk tool

- infrastructure/sdk.local.Dockerfile
Ticket: https://spryker.atlassian.net/browse/SDK-1713.
- Adjusted sdk.local.Dockerfile file to sync local user permissions.
> SDK-1713: change permission for local user

- composer.lock
- Ticket:
- https://spryker.atlassian.net/browse/SDK-1687
- https://spryker.atlassian.net/browse/SDK-1722
- https://spryker.atlassian.net/browse/SDK-1624
- merge: merge
Adjustments
- Adjusted `composer.json` to update `spryker-sdk/integrator` and `spryker-sdk/upgrder` dependencies.
Improvements
- Added code sniffer execution after the integration of the `Manifest` so changed code has proper code style.
- Improved `Upgrader` tool with the `--no-install` option for the composer installation.
- …
> Update upgrader and integrator

- .github/workflows/post-release.yml
Ticket: https://spryker.atlassian.net/browse/SDK-1777
* Added New sprykerci image.
> SDK-1777: SprykerCI image

- .github/workflows/post-release.yml
Added Buddy CI job trigger
https://spryker.atlassian.net/browse/SDK-1812
> SDK-1812: Add Spryker CI checks

- .github/workflows/post-release.yml
Added Buddy CI job trigger
https://spryker.atlassian.net/browse/SDK-1812
> SDK-1812: Add SprykerCI pipeline trigger

- composer.lock
Ticket: https://spryker.atlassian.net/browse/SDK-1989.
> SDK-1989: Upgrader update.

- composer.lock
Ticket: [SDK-1932](https://spryker.atlassian.net/browse/SDK-1932).
[SDK-1932]: https://spryker.atlassian.net/browse/SDK-1932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Azure Repos support in Spryker Code Upgrader

- src/Extension/Resources/config/task/SprykRunTask.yaml
https://spryker.atlassian.net/browse/SDK-1948
> SDK-1948 update help message

- composer.lock
Ticket: https://spryker.atlassian.net/browse/SDK-1975.
> SDK-1975: Fixed checking all packages & improved reading composer.

- src/Infrastructure/Service/ValueReceiver/QuestionFactory/PathQuestionFactory.php
- tests/Sdk/Unit/Infrastructure/Service/ValueReceiver/QuestionFactory/PathQuestionFactoryTest.php
Fix path issue
https://spryker.atlassian.net/browse/SDK-1799
> SDK-1799: Fixed relative path checks.

- config/packages/monolog.yaml
- infrastructure/newrelic/entrypoint.sh
- infrastructure/newrelic/newrelic.ini
- infrastructure/sdk.sprykerci.Dockerfile
- merge: squash
Fixes
- Internal improvements.
> Release 0.6.17

- composer.lock
Ticket: [SDK-2056](https://spryker.atlassian.net/browse/SDK-2056).
[SDK-2056]: https://spryker.atlassian.net/browse/SDK-2056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SDK-2056: Update upgrader and integrator

- composer.lock
- Developer(s): @DmytroKlymanSpryker
- Ticket: 
- Docs PR: ACADEMY_URL_HERE
- Release Group: URL_HERE
- merge: merge
Ticket: [SDK-2056](https://spryker.atlassian.net/browse/SDK-2056).
- Internal improvements.
[SDK-2056]: https://spryker.atlassian.net/browse/SDK-2056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SDK-2056: Updated upgrader and integrator dependencies.(#352)

- tests/Sdk/Acceptance/Telemetry/CodeSnifferTaskFixerCest.php
- tests/_support/AcceptanceTester.php
https://spryker.atlassian.net/browse/SDK-2076
> SDK-2076: Flickering test fix

- composer.lock
- Developer(s): @DmytroKlymanSpryker
- Ticket: 
- merge: merge
- Internal improvements.
> Update upgrader, integrator

- composer.lock
- infrastructure/installer_header.sh
Provided changes fix sed problems for os x and allow properly set up `spryker-sdk` alias.
Ticket: https://spryker.atlassian.net/browse/SDK-2032.
> SDK-2032: fixed installer for the os x.

- composer.json
- composer.lock
- Ticket: https://spryker.atlassian.net/browse/SDK-2584
- Release Group: URL_HERE
- merge: squash
Improvements
> Release 0.6.24

- .github/workflows/dependency-update-pr.yml
Ticket: https://spryker.atlassian.net/browse/SDK-1805
> SDK-1805 CI automation.

- config/packages/monolog.yaml
- config/services_sprykerci.yaml
- infrastructure/sdk.sprykerci.Dockerfile
- src/Infrastructure/Logger/NewRelicFormatter.php
- src/Infrastructure/Logger/TransactionNameNewRelicProcessor.php
- src/Infrastructure/Resources/config/services.yaml
- tests/Sdk/Unit/Infrastructure/Logger/NewRelicFormatterTest.php
- tests/Sdk/Unit/Infrastructure/Logger/TransactionNameNewRelicProcessorTest.php
https://spryker.atlassian.net/browse/SDK-2064
Ticket: {Ticket Link}.
> SDK-2064: NewRelic transaction name

- composer.lock
- Ticket: https://spryker.atlassian.net/browse/SDK-2883
- Docs PR: ACADEMY_URL_HERE
- Release Group: URL_HERE
- merge: squash
Improvements
-  Internal improvements and fixes.
> Release 0.6.33

- infrastructure/newrelic/entrypoint.sh
Ticket: https://spryker.atlassian.net/browse/SDK-2865.
> SDK-2865: Fixed message

- composer.json
- composer.lock
- Update evaluator
Ticket: [SDK-2359](https://spryker.atlassian.net/browse/SDK-2359).
[SDK-2359]: https://spryker.atlassian.net/browse/SDK-2359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Evaluator update

- infrastructure/sdk.sprykerci74.Dockerfile
- infrastructure/sdk.sprykerci80.Dockerfile
- infrastructure/sdk.sprykerci81.Dockerfile
- infrastructure/sdk.sprykerci82.Dockerfile
Ticket: [SDK-4942](https://spryker.atlassian.net/browse/SDK-4942).
[SDK-4942]: https://spryker.atlassian.net/browse/SDK-4942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SDK-4942: Add installation of the php ext-xsl

- composer.lock
- Ticket: 
- Release Group: URL_HERE
- merge: merge
> Release 0.6.68

- composer.json
- composer.lock
Ticket:
* [SDK-5559](https://spryker.atlassian.net/browse/SDK-5559).
* [SDK-5550](https://spryker.atlassian.net/browse/SDK-5550)
[SDK-5559]: https://spryker.atlassian.net/browse/SDK-5559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SDK-5550]: https://spryker.atlassian.net/browse/SDK-5550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SDK-5559: Solve vulnerability issues

- composer.json
- composer.lock
> SDK-4666: Update upgrader

- package-lock.json
> SDK-5559: Update npm packages

- composer.lock
Original PR: https://github.com/spryker-sdk/upgrader/pull/276
> SDK-5579: UX improvments

- .github/workflows/ci.yml
Ticket: https://spryker.atlassian.net/browse/SDK-5667
> Added php 8.2 to the ci.yml

- .github/workflows/ci.yml
- composer.lock
- Ticket: https://spryker.atlassian.net/browse/SDK-5667
- Release Group:
- merge: merge
Improvements
> Release 0.6.74

- .github/workflows/ci.yml
> SDK-5677: Add support of PHP 8.3

- .github/workflows/ci.yml
- composer.lock
Included commits: https://github.com/spryker-sdk/sdk/compare/0.6.74...0.6.75
Improvements
> Release 0.6.75

- .github/workflows/ci.yml
- composer.lock
Included commits: https://github.com/spryker-sdk/sdk/compare/0.6.75...0.6.76
> Release 0.6.76

- .github/workflows/ci.yml
- composer.lock
Included commits: https://github.com/spryker-sdk/sdk/compare/0.6.76...0.6.77
> Release 0.6.77

- .github/workflows/ci.yml
- composer.lock
Included commits: https://github.com/spryker-sdk/sdk/compare/0.6.77...0.6.78
> Release 0.6.78

- .github/workflows/ci.yml
- composer.json
- composer.lock
Included commits: https://github.com/spryker-sdk/sdk/compare/0.6.78...0.6.79
> Release 0.6.79

- composer.json
- composer.lock
Ticket: https://spryker.atlassian.net/browse/FRW-7429.
> Updated conposer.lock

- composer.json
- composer.lock
Ticket: https://spryker.atlassian.net/browse/FRW-7460.
> FRW-7460: Updated composer

- .github/workflows/ci.yml
- .github/workflows/post-release.yml
- README.md
- composer.lock
- phpstan.neon
- src/Extension/Converter/PrettierSnifferViolationReportConverter.php
Ticket: https://spryker.atlassian.net/browse/FRW-8801.
> FRW-8801 Upgraded PHP ver and updated composer.lock

- composer.lock
Ticket: https://spryker.atlassian.net/browse/FRW-8801.
> Rc resolved conflicts

- composer.json
- composer.lock
- infrastructure/sdk.sprykerci-8.3.Dockerfile
Ticket: https://spryker.atlassian.net/browse/FRW-8801.
> FRW-8801 Added sprykerci-83 docker image.

- composer.json
- composer.lock
Ticket: https://spryker.atlassian.net/browse/FRW-9570
> FRW-9570 Bumped the upgrader version.

- composer.json
- composer.lock
https://spryker.atlassian.net/browse/SUPESC-936
> SUPESC-936: Updated security checker
